
import os
import sys
import pandas as pd
from dotenv import load_dotenv

# Add parent dir to path to import gsheets service
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.services.gsheets import load_data as load_gsheets

load_dotenv()

SHEETS_TO_TABLES = {
    "User_Master": "users",
    "Contacts": "contacts",
    "Activities": "activities",
    "Master_Schedule": "master_schedule"
}

def clean_column_name(col: str) -> str:
    return col.strip().lower().replace(" ", "_").replace(".", "")

def get_sql_type(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return "bigint"
    elif pd.api.types.is_float_dtype(dtype):
        return "float"
    elif pd.api.types.is_bool_dtype(dtype):
        return "boolean"
    else:
        return "text"

def generate_schema(sheet_name, table_name):
    try:
        df = load_gsheets(sheet_name)
    except Exception as e:
        print(f"-- Failed to load {sheet_name}: {e}")
        return

    if df.empty:
        print(f"-- Sheet {sheet_name} is empty.")
        return

    df.columns = [clean_column_name(c) for c in df.columns]
    
    print(f"\n-- Table: {table_name}")
    print(f"CREATE TABLE IF NOT EXISTS {table_name} (")
    print("  id bigint generated by default as identity primary key,")
    print("  created_at timestamp with time zone default timezone('utc'::text, now()) not null,")
    
    for col in df.columns:
        sql_type = get_sql_type(df[col].dtype)
        # Avoid reserved words or conflicts if necessary, but Supabase is usually forgiving
        print(f"  {col} {sql_type},")
    
    print(");")
    print(f"alter table {table_name} enable row level security;")
    print("-- Policy: Allow all access for now (Development)")
    print(f"create policy \"Enable all for {table_name}\" on {table_name} for all using (true) with check (true);")

def main():
    target = sys.argv[1] if len(sys.argv) > 1 else None
    print("-- RUN THIS SQL IN SUPABASE SQL EDITOR --")
    for sheet, table in SHEETS_TO_TABLES.items():
        if target and table != target:
            continue
        generate_schema(sheet, table)

if __name__ == "__main__":
    main()
